### PR TITLE
Ratified

### PR DESCRIPTION
**Pull request by jjscheel**
Signed-off-by: Jeff Scheel <jeff@riscv.org>

### CODE REVIEW

**Review by joshuascheid — APPROVED** [review]
LGTM.

**Comment by jhauser-us** [comment]
This pull request cannot be merged until after #3 is merged.  We must not attach a *ratified* label on the wrong text.

**Review by joshuascheid — CHANGES_REQUESTED** [review]
Wait for #3.

**Review by aswaterman — APPROVED** [review]
LGTM.

**Pull request merged**
